-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.posts
(
    id uuid NOT NULL,
    content character varying(120) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.posts
    IS 'all data of the posts';

CREATE TABLE IF NOT EXISTS public.post_likes
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.posts
    ADD FOREIGN KEY (id)
    REFERENCES public.post_likes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;