services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "5433:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data 

      # precisa deletar isso, caso queira iniciar novamente o banco de dados
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres123"
    ports:
      - "16543:80"
    depends_on:
      - pg
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge